import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { HomePage } from "@/src/components/home/home-page";
const inter = Inter({ subsets: ["latin"] });

interface EventCategory {
  id: string;
  title: string;
  description: string;
  image: string;
}
export default function Home({ data }: { data: EventCategory[] }) {
  return (
    <main>
      <Head>
        <title> Events App</title>
        <meta name="description" content="Generated by create Next App" />
        <link rel="icon" href="calendar.png" />
      </Head>
      <HomePage data={data} />
    </main>
  );
}
export async function getServerSideProps() {
  const data = await import("@/data/data.json");

  // Access event categories from the imported data
  const eventCategories: EventCategory[] = data.default.events_categories;

  return {
    props: {
      data: eventCategories,
    },
  };
}
